### ISSUE TITLE
Disappearing timeline on Windows high contrast mode

### ISSUE THREAD

**Issue by cgruber-uos** [polimediaupv/paella-ethz#10]
In case you activate the high contrast mode in Windows, e.g. shortcut left Alt + left Shift + Print Screen the timeline disappears: 

![2022-12-12 15_00_36-Greenshot](https://user-images.githubusercontent.com/101632236/207064843-a74e8b11-d1b5-427d-9d5c-7a138a4a0bf7.png)

**Comment by miesgre** [comment]
@cgruber-uos Player updated. Can you test it?
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote
![photo_2023-02-27 12 02 07](https://user-images.githubusercontent.com/2735202/221561185-f715ba77-8bb8-44e5-bace-f0e391494f4b.jpeg)

**Comment by ClemensGruber** [comment]
Unfortunately still the same issue on Win 11 with latest FF

Btw the volume slider is also not popping up / visible by clicking on the loudspeaker. 

![2023-03-02 23_28_12-Greenshot](https://user-images.githubusercontent.com/36139413/222574467-93f67271-6e53-41fa-8e70-1d514f207631.png)

**Comment by miesgre** [comment]
Thanks @ClemensGruber. It should work now in Firefox!
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote

**Comment by ClemensGruber** [comment]
Yes! Timeline and playhead are visible now

![2023-03-08 19_11_53-Greenshot](https://user-images.githubusercontent.com/36139413/223795684-b42e6942-427f-415e-86ce-c36e24ce5a62.png)
