### ISSUE TITLE
Automatic fading out of the navigation bar leads to unusable behavior

### ISSUE THREAD

**Issue by cgruber-uos** [polimediaupv/paella-ethz#11]
After around 5 seconds without any keyboard or mouse action the navigation bar is automatically fading out: 

![2022-12-12 15_05_35-Greenshot](https://user-images.githubusercontent.com/101632236/207065539-23ad8984-032e-4f73-be20-e09174c29d02.png)

This leads to unusable behavior, especially tab navigation is no more possible. You have to move the mouse or make any keyboard action first do show the navigation and then you can tab on. Very annoying and complicated for people with motoric disabilities.

**Comment by oas777** [comment]
We have to find a compromise here because the control bar disappearing is necessary or at least favourable if it covers part of the video: Cf. https://video.ethz.ch/speakers/lecture.html.

**Comment by cgruber-uos** [comment]
That's an interesting and important observation because I thought that the navigation bar is totally underneath the video / slide area! In the new "ETH player" (you may test it via https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote) this seems the case to be, as you can see here: 

![2023-01-06 15_45_27-Greenshot](https://user-images.githubusercontent.com/101632236/211035300-c4f851e1-0d34-4565-8a71-772a2bc1ce72.png)
 
![2023-01-06 15_45_23-Greenshot](https://user-images.githubusercontent.com/101632236/211035322-3f6fc3f3-b148-4139-b227-ad7ff3efccb8.png)

Perhaps some pixel are cropped when you observe the red bag? Intentionally or accidentally? 

While the "old" player layout did not cut any part in 1 : 1 relation slides : video

![2023-01-06 15_34_47-Paella Player – Mozilla Firefox](https://user-images.githubusercontent.com/101632236/211036580-dd5aac2d-65da-413e-8a92-3cd8c79fc0c1.png)

But did hide video parts with the setting "big video" (what the ETH design do not!)

![2023-01-06 15_36_41-Paella Player – Mozilla Firefox](https://user-images.githubusercontent.com/101632236/211036751-efb40811-888c-4b2c-97c0-47001896f6cb.png)

Perhaps the overlay navigation does only effect single track videos (presenter only), so could we have an example with the new player and a single track video (e.g. by modifying "id=belmar-multiresolution-remote" in https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote)

**Comment by oas777** [comment]
Miguel, could you please upload a single (16:9) video to test this?

**Comment by miesgre** [comment]
> Miguel, could you please upload a single (16:9) video to test this?

There are more tests in the [repository](https://github.com/polimediaupv/paella-ethz/tree/main/repository_test/repository).

This https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-single and this
https://polimediaupv.github.io/paella-ethz/?id=hls-multiaudio are 16:9

**Comment by oas777** [comment]
Thanks, Miguel.

Clemens, does the control bar have to be visible all the time? YouTube makes its controls disappear after a couple of seconds: 
https://tinyurl.com/2ovj3ze9.

**Comment by cgruber-uos** [comment]
Goal would be to have access to all control bar functions again after a disappeared control bar -- also with tab navigation. Thats possilble at YouToub by pressein just tab. This does not work in Paella. The only workaround I found was to stop the video with space key and then the control bar showed up again, just using the tab key does not show the control bar in paella. Can we add this behavior at Paella Miguel / @miesgre ?

**Comment by miesgre** [comment]
@cgruber-uos We updated the player. Can you test it works as expected?
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote

**Comment by ClemensGruber** [comment]
Yes! Now it is as expected, a tab press shows now the navigation bar again and focus the play/pause button!

**Comment by miesgre** [comment]
Thanks @ClemensGruber
