### ISSUE TITLE
Design: Adapt the play button

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#12]
https://tinyurl.com/2gox7lms has an "empty" play button which is also a different triangle: Cf. https://tinyurl.com/2gazthq2 and attachment.
![play](https://user-images.githubusercontent.com/1752342/211006805-52ecf0f4-5031-4bf4-9355-245266cf5c6b.png)

**Comment by oas777** [comment]
![play](https://user-images.githubusercontent.com/1752342/211042088-bcbc4f45-4a5b-4bf0-bcc5-f16a695bde34.png)

**Comment by miesgre** [comment]
Icon changed in commit c544c12d6fba728116ba51fa72b2176d2cbd7938!
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote

**Comment by oas777** [comment]
Confirmed, thanks.
