### ISSUE TITLE
Design: Adapt the -/+ 10s buttons

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#13]
Compared to https://tinyurl.com/2gox7lms, they are too large and not aligned horizontally. Please also check the font is the same as other buttons in the control bar.
![play](https://user-images.githubusercontent.com/1752342/211007425-a3a250f7-089a-4d59-b1fe-6b5ae973f1f4.png)

**Comment by miesgre** [comment]
@oas777  We updated the player. Can you test it works as expected?
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote

**Comment by oas777** [comment]
Almost... the "Forward 10 seconds" button is cut off on the right side. And maybe you could align the numbers "10" with the playback rate number horizontally?
<img width="237" alt="10seconds" src="https://user-images.githubusercontent.com/1752342/221436321-f2b06f21-3baa-4f2b-b816-cf9ffa46e600.png">

**Comment by oas777** [comment]
<img width="251" alt="10seconds" src="https://user-images.githubusercontent.com/1752342/221436438-a462ace5-c8bb-4604-958b-0f1e246dee7f.png">

**Comment by miesgre** [comment]
> Almost... the "Forward 10 seconds" button is cut off on the right side. 
> <img alt="10seconds" width="237" src="https://user-images.githubusercontent.com/1752342/221436321-f2b06f21-3baa-4f2b-b816-cf9ffa46e600.png">

It's a bug in Windows, in OSX works correctly. We will try to fix it.

> And maybe you could align the numbers "10" with the playback rate number horizontally? 
> <img alt="10seconds" width="251" src="https://user-images.githubusercontent.com/1752342/221436438-a462ace5-c8bb-4604-958b-0f1e246dee7f.png">

The time text is aligned to be vertically center and the back/forward icons are aligned in the same size and positions as the rest of the icons (play, volume, etc...). 

In Lisa's designs the text is not aligned:
![Captura de pantalla 2023-02-27 a las 11 21 32](https://user-images.githubusercontent.com/2735202/221538288-55c0211a-0e58-414b-a143-9e93505022e7.png)

But, If you want it aligned we can:

1. Down the time text:
![Captura de pantalla 2023-02-27 a las 11 08 05](https://user-images.githubusercontent.com/2735202/221538591-c65cd7be-0e1b-465d-933f-983cbe5979f2.png)

2. Up the back/forward icons. But the there will not be aligned to the rest of the icons:
![Captura de pantalla 2023-02-27 a las 11 06 11](https://user-images.githubusercontent.com/2735202/221539241-4741285f-6547-41d7-b9d9-de7d9487916c.png)

**Comment by oas777** [comment]
You're right, Lisa didn't align them, but I like the second option better: 
![image](https://user-images.githubusercontent.com/1752342/221567476-5257a6ac-33d0-4021-b1e0-e8992e53858b.png)
What do you think? What does Carlos think?

**Comment by miesgre** [comment]
I prefer the lisa's design.  The second option, the icon is not aligned inside the button and I find it annoying. But is'a a personal opinion. 
![221567476-5257a6ac-33d0-4021-b1e0-e8992e53858b](https://user-images.githubusercontent.com/2735202/221576135-030981e1-13d0-4897-90f2-e8567a773772.png)

@turro What do you think?

**Comment by miesgre** [comment]
I aligned the text as second option.
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote

**Comment by miesgre** [comment]
> I aligned the text as second option. 
> Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote

It should also fix the cut off text in windows

**Comment by oas777** [comment]
Looks, good, thanks.
