### ISSUE TITLE
Design: When opening one "button menu", the other one should close automatically

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#16]
If you click on "Playback Rate", the menu remains open until you click again. If you don't and click on "Settings" instead, two menus are open at the same time, which probably shouldn't happen.

Cannot add screenshot.

**Comment by oas777** [comment]
PS: In Lisa's suggested design, the menu is moving from one button to the other, cf. https://tinyurl.com/2gox7lms.

**Comment by miesgre** [comment]
@oas777 It should be fixed now. Can you test it works as expected?
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote

**Comment by oas777** [comment]
Looks good, thanks!
