### ISSUE TITLE
Design: Concept for zooming (in dual video setups)

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#20]
To be discussed.

**Comment by oas777** [comment]
Currently, there's no symbol for the zoom in the control bar and this seems to be working fine here at ETH. 
And the control bar is pretty much "full" on both sides. 
And I don't think anyone would be interested in "Zoom settings" hidden in "Settings". And the "orientation window" (https://video.ethz.ch/events/2023/aaz.html) is gone, which is good.

So if there are no specific problem with zooming in dual video setting, I think we're good here - or do you have other requirements?

**Comment by oas777** [comment]
PS: Maybe change "ALT" to "Alt" in the text shown when scrolling in the video?

**Comment by miesgre** [comment]
> PS: Maybe change "ALT" to "Alt" in the text shown when scrolling in the video?

Paella 6 shows `Use Alt+Scroll to zoom the video`
Paella 7 shows `Press ALT to zoom`

What about returning to Paella 6 text? or maybe `Use Alt+Scroll to zoom`?

**Comment by oas777** [comment]
"Use Alt+Scroll to zoom" works for me.

**Comment by miesgre** [comment]
> So if there are no specific problem with zooming in dual video setting, I think we're good here - or do you have other requirements?

No, for me it's good!

> "Use Alt+Scroll to zoom" works for me.

Done!
