### ISSUE TITLE
Design: Check buttons/symbols for video windows control

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#21]
The symbols used to deal with individual videos (moving in slides, maximizing/minimizing, closing) are similar to the ones Lisa suggested, but somehow different in line strenght/width and size. Could you please check with Lisa's repository?

**Comment by miesgre** [comment]
Player updated. Please check!
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls

**Comment by oas777** [comment]
Video doesn't load at https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls.

**Comment by oas777** [comment]
No, these are not the ones Lisa designed:

![grafik](https://user-images.githubusercontent.com/1752342/229181171-389e0b8c-4c9f-414c-9d7a-cdb6208716ec.png)

Cf. https://www.figma.com/file/7wbHm2GkTXsWfg9omeb7i6/Redesign?node-id=0-1&t=rjiYhXsLiIjvPcKs-0 (lower left corner, you have to zoom in)

**Comment by oas777** [comment]
PS: 
![paella icon-button-small](https://user-images.githubusercontent.com/1752342/229181440-bf28812a-d780-4ebe-84d5-fe2d4960a2e7.png)
![paella icon-button-small(4)](https://user-images.githubusercontent.com/1752342/229181447-08d5311c-a7ef-45ac-b645-09753d6474f6.png)
![paella icon-button-small(3)](https://user-images.githubusercontent.com/1752342/229181450-1d2f6c8f-e44b-4226-bf7b-5dc3a958bee2.png)
![paella icon-button-small(2)](https://user-images.githubusercontent.com/1752342/229181451-2e8fe477-0383-4617-8882-e58c59e7533b.png)
![paella icon-button-small(1)](https://user-images.githubusercontent.com/1752342/229181452-57a1c84a-0af5-4951-8026-4ac4156a4444.png)

**Comment by miesgre** [comment]
Sorry for the error. Icons updated.
Please check!
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls

**Comment by oas777** [comment]
Thanks, this looks good! Some remaining details:

Audio level: Can you make the bar blue according to the audio level? Cf.
![grafik](https://user-images.githubusercontent.com/1752342/232040067-c349dd69-7c40-435f-9abf-92590f90ace5.png)

Minimize video: Can you replace your symbol with Lisa's?

![grafik](https://user-images.githubusercontent.com/1752342/232041268-05663b42-0dfb-4344-a8e8-b22c5c614440.png)
![grafik](https://user-images.githubusercontent.com/1752342/232041429-4b8aa403-074c-4619-9a4c-8eaf70d30644.png)

Video layout: Remove the symbols and replace with text:

![grafik](https://user-images.githubusercontent.com/1752342/232041826-4b91bf41-2165-4e86-98c3-4e994d861163.png)
![grafik](https://user-images.githubusercontent.com/1752342/232041863-c16d8d3d-213a-4dbe-8a48-5f007a2b6a92.png)

Show video slides: Use Lisa's symbol instead of empty squares:

![grafik](https://user-images.githubusercontent.com/1752342/232042211-56721c2c-8b44-40a2-b702-c9026a0f1389.png)
![grafik](https://user-images.githubusercontent.com/1752342/232042369-4646b4cd-5c31-4508-b40f-7ae11e65df8e.png)

I know this is tedious, apologies...

**Comment by miesgre** [comment]
> Thanks, this looks good! Some remaining details:
>
> Minimize video: Can you replace your symbol with Lisa's?
> 
> ![grafik](https://user-images.githubusercontent.com/1752342/232041268-05663b42-0dfb-4344-a8e8-b22c5c614440.png) ![grafik](https://user-images.githubusercontent.com/1752342/232041429-4b8aa403-074c-4619-9a4c-8eaf70d30644.png)
> 

## How layout buttons works in current paella layout:
1.	Starting with a side by side view, you can click to maximize any video  
![Captura de pantalla 2023-04-20 a las 12 11 21](https://user-images.githubusercontent.com/2735202/233343924-f0fe0414-d29e-49c3-8626-e77dc988f549.png )
2.	Then you can return to side by side view by clicking the side my side button.
![Captura de pantalla 2023-04-20 a las 12 11 48](https://user-images.githubusercontent.com/2735202/233343915-693ef661-0e67-4c6a-9ce0-78efa2c063ed.png)


## Lisa designs
1.	In the same way, you can click to maximize, to maximize the video 
![Captura de pantalla 2023-04-20 a las 12 08 34](https://user-images.githubusercontent.com/2735202/233345778-64aa6743-df59-407d-a669-78dbe2609ac2.png)
2.	Then you have two different buttons (with different icons) 
![Captura de pantalla 2023-04-20 a las 12 08 49](https://user-images.githubusercontent.com/2735202/233345836-b1874557-75d6-4cbb-8132-6f60b4c63bc7.png)

## Questions
-	Minimize button, should go to side by side? Or should minimize this videos and maximize the other? Same for maximize button?
-	Both icons should return to side by side view? Why are both different?
-	If maximize button should maximize this video, and minimize, minimize the video, how can we go back to side by side?

**Comment by miesgre** [comment]
Sorry, there are some hover-over labels that are not updated, and It is causing confusion.

Meaning of the symbols:

![image](https://user-images.githubusercontent.com/1752342/233382360-4b550e53-33af-440a-9d85-2339bff8592d.png) 

The idea of this symbol is to go to slide by slide (50%, 50%) - same size.
This is the reason it is used in 1 video layout and 2 video layout (when one video is maximized).
We have to look for a good hover-over text.

![image](https://user-images.githubusercontent.com/1752342/233383686-7cf643ca-9eaf-416f-89b9-5720f8a4a0b3.png) 
The idea of this symbol is to maximize one video (when dual video layout).
And is only visible when dual video layout are at 50%, 50% (same size).

For me, the problem I see using what you are proposing is when dual video layout with one video maximized:

> * Once he did, the videos are different in size and offer different options therefore: Maximise or minimise.
> 
> ![image](https://user-images.githubusercontent.com/1752342/233383686-7cf643ca-9eaf-416f-89b9-5720f8a4a0b3.png) ![image](https://user-images.githubusercontent.com/1752342/233384585-3a387dc6-c505-4cba-8f5a-a7cf7dbbeb72.png)

So, the symbol "maximize" has two different meaning:
- In dual video layout (same size) it means "Maximize one video" going to 25%, 75% video layout
- But in (25%, 75% layout) clicking that symbol (that only will be in minimized video) end with videos al 50%, 50% and not (75%, 25%) as I expected 


What do you think? Which one makes the most sense?
@oas777? @turro?

**Comment by oas777** [comment]
Sorry for my late reply. I see your point. So use

![image](https://user-images.githubusercontent.com/1752342/236053849-052e6872-d676-4a4e-9348-e81120e9bccd.png)

to make two videos equally large (when one is small).  Hover-over: "Align videos".

Use

![image](https://user-images.githubusercontent.com/1752342/236055046-4d633d44-7fab-460f-949a-d7ec7865cc5b.png)

to increase the size of one video. Hover-over: "Enlarge video" (because switching to one video would be "Maximize").

Don't use

![image](https://user-images.githubusercontent.com/1752342/236055286-f38308b3-d69d-49ab-b6a8-66b2f64d623f.png)

at all.

Makes sense?

**Comment by miesgre** [comment]
Done.
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls

**Comment by oas777** [comment]
Sorry, but I only just saw

- https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls has some German hover-over information:
![image](https://github.com/polimediaupv/paella-ethz/assets/1752342/6b13b235-a5c1-4f00-a26e-6e0f0e38b304)
![image](https://github.com/polimediaupv/paella-ethz/assets/1752342/30269543-3515-4a73-90ca-58408c74f469)
Is this due to my browser settings?
- Also, some hover-over information (e. g. "Seek video to the next slide") are not in https://github.com/polimediaupv/paella-core/ - where is the "ethz" vocabulary?

**Comment by miesgre** [comment]
@oas777 Yes. If you have your browser in German, paella will use German.

Localization for ethz is here: https://github.com/polimediaupv/paella-ethz/tree/main/src/i18n

**Comment by miesgre** [comment]
> Really? I'm looking at https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls again and now all hover-over texts are in English with a German browser. So I cannot reproduced this. Let's revisit when/if we fully translate Paella to German.

Yes, But I was making some tests and this part was not working when you tested. Now is fixed. 
You should see it in German.


> PS: Is that a new symbol for "Align videos"? ![grafik](https://user-images.githubusercontent.com/1752342/240236839-d801794b-b759-47a3-9f40-bdd7957a3d29.png)

No. There is a problem with this icon. We are going to fix it.

**Comment by oas777** [comment]
Let's look at "hover-over" and "translation" separately. This one is fixed.
