### ISSUE TITLE
Provide new test video with two 16:9 source

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#24]
While I like the fact that I have been testing Paella Player with the same video for years now, I would like to see a demo/test video with two sources in a 16:9 format because most presentations are in this format nowadays. This would allow some further testing with respect to the positioning of the videos in different layouts. Thanks!

**Comment by miesgre** [comment]
New test uploaded.
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls

Normal view:
![Captura de pantalla 2023-03-14 a las 11 40 19](https://user-images.githubusercontent.com/2735202/224976022-203e78e7-1f8b-4710-8a09-153bed3fcf3b.png)

Screen small view:
![Captura de pantalla 2023-03-14 a las 11 40 40](https://user-images.githubusercontent.com/2735202/224976078-ee89b6f1-5ca2-4332-b94a-f7c06746ddf2.png)

**Comment by oas777** [comment]
Thanks!
