### ISSUE TITLE
Play Buttons

### ISSUE THREAD

**Issue by Melanie-Koller** [polimediaupv/paella-ethz#25]
Why are there 3 play buttons at the start? And you can click everywhere to start/stop the video. 
![Bildschirm­foto 2023-03-03 um 08 32 50](https://user-images.githubusercontent.com/57887263/222661338-a71c6012-44f5-4119-9e43-a377c96fca04.jpg)

**Comment by oas777** [comment]
This one I can solve. There is only one play button in the middle, the other two are images placed in the videos for test purposes. You can ignore them.

**Comment by ClemensGruber** [comment]
See #2 Player preview: Too much play buttons, differences with actual player
