### ISSUE TITLE
Toggle Play/Pause with Spacebar

### ISSUE THREAD

**Issue by Melanie-Koller** [polimediaupv/paella-ethz#26]
This dosen't work, if you were before on volume, playback speed, backward/forward 10 seconds. It also dosen't work on video slides or full screen.

**Comment by miesgre** [comment]
Player updated. Now `spacebar` key plays/pause the video, but does not act as `click` in buttons. `Enter` key acts as `click`
Demo: http://localhost:8080/?id=belmar_16_9_hls

**Comment by oas777** [comment]
Sorry for the delay, but http://localhost:8080/?id=belmar_16_9_hls is not available anymore. Can we test with a new setup?

**Comment by miesgre** [comment]
Sorry, copy&paste error. Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls

**Comment by oas777** [comment]
Works on Chrome (Windows). Can you confirm, Melanie?

**Comment by oas777** [comment]
PS: With this demo, the video quality does not change, cf. https://github.com/polimediaupv/paella-ethz/issues/28#issue-1623718172.

**Comment by Melanie-Koller** [comment]
Yes, I confirm that.
