### ISSUE TITLE
Select video quality symbol: Fuzzy and too small

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#31]
![grafik](https://user-images.githubusercontent.com/1752342/229182767-1cc6c998-a8bd-4e07-b8d8-dcea82541d9f.png)
Looks fuzzy and "auto" is not centered. Also, it's too small:

![grafik](https://user-images.githubusercontent.com/1752342/229182902-fa24258a-3fbc-4981-bd55-3101ceadb9d0.png)

**Comment by miesgre** [comment]
We removed the white background and not It is only text in the same way as other plugins.
![Captura de pantalla 2023-04-19 a las 13 38 28](https://user-images.githubusercontent.com/2735202/233064272-48659c26-b23a-4871-91ed-1703c6cd8ab8.png)

Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls

**Comment by oas777** [comment]
"Auto" looks good, but with this video I cannot switch to other qualities to check.

**Comment by miesgre** [comment]
@oas777 It has multiple qualities. Under settings button.

![Captura de pantalla 2023-04-20 a las 11 57 34](https://user-images.githubusercontent.com/2735202/233332051-441c8e06-803e-4a47-881a-05537b021aec.png)


Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls

**Comment by oas777** [comment]
Yes! The font is still fuzzy on my large monitor, 

![image](https://user-images.githubusercontent.com/1752342/233370441-9d7f2fc0-6613-40c4-8f73-14e04a23f1ae.png)

but that's probably the local problem described in

https://github.com/polimediaupv/paella-basic-plugins/issues/3.
