### ISSUE TITLE
Naming and wording

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#32]
Some suggestions on (re-)naming features and (hover-over) information:

- "Play/pause" instead of "Play and pause button"
- "Playback rate" instead of "Switch the playback speed"
- "Volume" instead of "Change volume"
- "Settings" has no hover-over currently (?)
- "Video quality" instead of "Select video quality"
- "Video layout" instead of "Switch the video layout"
- Submenu: "Video layout" instead of "Video Layout"
- "Keyboard shortcuts" instead of "Keyboard Shortcuts"
- Keyboard shortcuts: "Go forward 10 seconds" instead of "Forward 10 seconds"
- Keyboard shortcuts: "Toggle captions" instead of "Toggle Captions"
- Keyboard shortcuts: "Close pop-up" instead of "Close Pop Up"
- "Show slides" instead of "Show video slides"
- "Fullscreen" instead of "Toggle fullscreen"

**Comment by miesgre** [comment]
Done!

Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls

**Comment by miesgre** [comment]
Updated labels in https://github.com/polimediaupv/paella-core/commit/8d4964856446f6da9cd8ad4aba0cc7b765fa2ced and https://github.com/polimediaupv/paella-basic-plugins/commit/326b6573dbae8d0f00a04981430afa51763eb298.

Waiting for the new paella versions to be released

**Comment by miesgre** [comment]
> Almost: Keyboard shortcuts: "Go forward 10 seconds" instead of "Forward 10 seconds". That was my mistake: It should be "Forward 10 seconds", just like "Backward 10 seconds" - sorry!

Done!

**Comment by oas777** [comment]
+1
