### ISSUE TITLE
Change symbol for Closed captions?

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#35]
I think we agreed with Clemens not to use the "CC" symbol but the one similar to the YouTube one:

![grafik](https://user-images.githubusercontent.com/1752342/232833185-8272b48f-8deb-4860-83a4-725452f6934c.png)

As part of the control bar (here, the "slide preview" symbol is missing in Lisa's design): 
![grafik](https://user-images.githubusercontent.com/1752342/232833529-7d753091-f259-44b7-b150-eeef7e59cc27.png)

YouTube: 
![grafik](https://user-images.githubusercontent.com/1752342/232834119-14988f4c-75d4-4fdd-8178-9e5cc534e68e.png)

**Comment by miesgre** [comment]
Icon updated to Lisa's design!
![Captura de pantalla 2023-04-19 a las 9 36 04](https://user-images.githubusercontent.com/2735202/233003028-dc256a66-128b-4db7-81b7-5a907b62456a.png)

Test:  https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls

**Comment by oas777** [comment]
That part of the control bar looks very, very good know, thanks for your patience!
