### ISSUE TITLE
Muted video with audio on (Chrome)?

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#36]
In Chrome (Windows), https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls starts with the audio symbol indicating mute

![grafik](https://user-images.githubusercontent.com/1752342/232835165-9c193079-75d8-402f-96cd-94ec3ea53088.png)

- but there is audio. Not so in Edge. Can't test Firefox.

**Comment by miesgre** [comment]
Bug fixed in `paella-core`. 

Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls

**Comment by oas777** [comment]
Fixed!
