### ISSUE TITLE
Menu "Settings" and sub-menu "Keyboard Shortcuts" are not closing when clicking e.g. on the video

### ISSUE THREAD

**Issue by cgruber-uos** [polimediaupv/paella-ethz#4]
An opened "Settings" menu is only closable by clicking on the "Settings" headline. In many other applications it is common behavior to click outside the menu element, e.g. on the video or background to close a menu. This is not possible at "Settings". Clicking outside (red cycle) leads to no change. Menu is still open. 

![2022-12-12 12_30_00-Greenshot](https://user-images.githubusercontent.com/101632236/207035820-5e413462-0d41-40e1-a727-7df23ee5f1ec.png)

Same for the sub-menu "Keyboard Shortcuts". Clicking outside the menu (red cycle) leads to no change and a still opened menu: 

![2022-12-12 12_30_08-Greenshot](https://user-images.githubusercontent.com/101632236/207035833-3c004d7b-48c6-4161-bd0a-27eb9ed65f5b.png)

Different -- and expected -- behavior on the "video layout" sub-menu. In case I click with a open "video layout" menu on the player background (green cycle) the sub-menu is closed! As I would expect it from a user perspecitve. 

**We should implement this behavior also for the other two menus "Settings" and "Keyboard Shortcuts"!**

![2022-12-12 12_30_17-Greenshot](https://user-images.githubusercontent.com/101632236/207035846-491e20e3-6c8d-4411-92b6-48f342124631.png)

**Comment by miesgre** [comment]
Issue #16 is also related.

**Comment by oas777** [comment]
Confirmed for Chrome and Firefox (Windows). "Switch the video layout" still needs two clicks though to disappear.

**Comment by miesgre** [comment]
@oas777 It is fixed now. 
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote

**Comment by oas777** [comment]
Looks good, thanks!

**Comment by ClemensGruber** [comment]
Nearly done I would say. Settings pop up closing automatically by clicking on the most UI elemts, e.g. clicking on the main video area - thanks for fixing that! - playback rate dropdown, scrubber ... marked with a green checkmark. 

But clicking on some other UI elements, red marker, does still not close the settings menu, that are
- play / pause button 
- ffw and frw
- mute / unmute (loudspeaker icon, the appearing volume slider is working!)
- show slides 

![2023-03-02 22_36_53-Greenshot](https://user-images.githubusercontent.com/36139413/222562683-efcaffbd-1401-466f-be5f-c879a1ecece9.png)

**Comment by miesgre** [comment]
Thanks @ClemensGruber! It is fixed now.
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote
