### ISSUE TITLE
Fullscreen symbol

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#40]
... almost: Shouldn't the symbol
![image](https://user-images.githubusercontent.com/1752342/236213634-8ffc0d51-373f-4fe4-95cd-217c3a37946f.png)
have arrows the other way round, indicating the video will get smaller when you exit fullscreen? Or use something like YouTube?
![image](https://user-images.githubusercontent.com/1752342/236214733-03347a3f-d845-4104-83e3-01743786f9a6.png)

**Comment by miesgre** [comment]
Done!
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls

**Comment by oas777** [comment]
Perfect, but...
