### ISSUE TITLE
Mute audio symbol is not central

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#42]
Didn't see that before:
![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/bc4eea4f-cc3a-4aab-830a-c0b58bc45a9e)

**Comment by miesgre** [comment]
Yes, the mute icon is not centered because we use the max volume icon to center all volume icons.
The "speaker" is constant in all images.

if we centered the icons, when changing from one to another, the icon would move. as if jumping or dancing

What do you think? @oas777? @turro?

![volume](https://github.com/polimediaupv/paella-ethz/assets/2735202/5ee4ad89-b52e-48c5-aad1-c7bf81f04f53)

**Comment by oas777** [comment]
Yes, I remember the "dancing effect". I presume the only way to solve it is to make them equally wide in "on" and "mute". Either in YouTube/Vimeo style

![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/7b91f8d7-640e-4586-aa66-ac3e6b5bb365)
![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/aa2cabc8-ccda-463a-8ce3-672bb62c403c)

**Comment by oas777** [comment]
PS: I like Netflix more...

**Comment by oas777** [comment]
Yes and no: YouTube and Vimeo (above) have the same symbol in both positions (speaker and waves), only it's crossed through when the postion is "mute". Netflix has two different symbols (speaker and waves vs. speaker and cross). But all of these are centered.

**Comment by miesgre** [comment]
Icon changed! Opinions?

**Comment by oas777** [comment]
Works for me. No dancing. Thanks!

**Comment by miesgre** [comment]
I updated also the other version:

- https://github.com/polimediaupv/paella-ethz/blob/main/public/ethz_theme/icons/volume-mute.svg
- https://github.com/polimediaupv/paella-ethz/blob/main/public/ethz_theme/icons/volume-mute-cross.svg

We have to decide which one to use

**Comment by oas777** [comment]
I'm in favor of volume-mute-cross.svg. You? @turro?

**Comment by turro** [comment]
I'm also for volume-mute-cross.svg, The other one gives me a bit of cognitive overhead because it feels to me like "very loud but muted"

**Comment by miesgre** [comment]
Icon changed to `volume-mute-cross.svg` 😄
