### ISSUE TITLE
Hover-over texts

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#43]
https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls says "Seek video to the previous slide" and "Seek video to the next slide". Could you please make this "Go to previous segment" and "Go to next segment"? It's not always slides, it could also be a document camera or even a regular video (depending on your settings) and still a segmentation would produce "segments". 

Also, the issue with mixed English and German texts in hover-over mentioned in https://github.com/polimediaupv/paella-ethz/issues/21#issuecomment-1559159884 is still there.

**Comment by miesgre** [comment]
> https://polimediaupv.github.io/paella-ethz/?id=belmar_16_9_hls says "Seek video to the previous slide" and "Seek video to the next slide". Could you please make this "Go to previous segment" and "Go to next segment"? It's not always slides, it could also be a document camera or even a regular video (depending on your settings) and still a segmentation would produce "segments".

Texts updated!
 
> Also, the issue with mixed English and German texts in hover-over mentioned in [#21 (comment)](https://github.com/polimediaupv/paella-ethz/issues/21#issuecomment-1559159884) is still there.

The problem is that paella is not fully translated to german. Only a few labels are in german.
See https://github.com/polimediaupv/paella-ethz/issues/27

**Comment by miesgre** [comment]
Which texts? Translate them into German?

**Comment by oas777** [comment]
No, the hover-over texts. They said "Seek video to the previous slide" and "Seek video to the next slide" and I wanted this to be changed to "Go to previous segment" and "Go to next segment" (because videos without slides could be segmented too). But now I think the overall majority will be slides, so the current solution is good. Sorry for overthinking.
