### ISSUE TITLE
Slide preview bar should be transparent

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#45]
Not the same as the control bar:
![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/65641543-fe0e-4232-87a6-821db033ecf7)

**Comment by miesgre** [comment]
Completely transparent? or partially?

| | Preview |
| - | ------------- |
| 0% | ![0](https://github.com/polimediaupv/paella-ethz/assets/2735202/8515f247-adbe-447a-8be1-c67224eb7dcd)  |
| 20% | ![20](https://github.com/polimediaupv/paella-ethz/assets/2735202/cbcedaea-1861-4242-8a34-cb6c16bf055f) | 
| 60% | ![60](https://github.com/polimediaupv/paella-ethz/assets/2735202/329ec0e0-54ee-4f9d-bea1-aebffc519427) | 
| 100% | ![100](https://github.com/polimediaupv/paella-ethz/assets/2735202/5fdaf88d-1c56-4ce1-8f47-501240d5b938) | 


@oas777, Which one do you prefer?

**Comment by oas777** [comment]
60% please.

**Comment by miesgre** [comment]
Please check https://polimediaupv.github.io/paella-skins/.
If skin is correct I will update ethz repository.

**Comment by oas777** [comment]
Migratin this to Tobira.
