### ISSUE TITLE
Subtitle bar should be somewhat transparent - and smaller

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#47]
![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/71ae3328-0710-4c41-bd32-cae4f27dc836)

Maybe like
![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/82224602-d3da-4565-9bfd-07db6bc057c7)
or
![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/590dc543-57ca-4bd1-94e6-edea8d732797)

**Comment by miesgre** [comment]
I made it semi-transparent and adjusted the size of the subtitles box.
Please check https://polimediaupv.github.io/paella-skins/.

**Comment by oas777** [comment]
Looks good. Unless the box is "pumpin'":

https://github.com/polimediaupv/paella-ethz/assets/1752342/1e30c13f-c6a2-4cd9-8db4-21a5f58270ef

Happened in Firefox and Chrome on Windows.

**Comment by miesgre** [comment]
Sorry. I was testing the changes with the video paused and didn't notice the problem. Fixed!
https://polimediaupv.github.io/paella-skins/

**Comment by oas777** [comment]
All good.
