### ISSUE TITLE
Subtitle menu: Overlapping text 

### ISSUE THREAD

**Issue by oas777** [polimediaupv/paella-ethz#48]
Only in Chrome:

![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/3d51bf4e-3ac9-44af-8eb2-20540afecb0e)

Firefox has no problems:

![grafik](https://github.com/polimediaupv/paella-ethz/assets/1752342/d9459479-9b93-41fe-bf8b-9e07ac98d6b4)

**Comment by miesgre** [comment]
I can not reproduce it.
![Captura de pantalla 2023-11-03 a las 11 12 42](https://github.com/polimediaupv/paella-ethz/assets/2735202/a37f9f45-b7f5-4dc8-ae67-746630b5e8d0)

I tested a more large text, but with the same result.
![Captura de pantalla 2023-11-03 a las 11 12 26](https://github.com/polimediaupv/paella-ethz/assets/2735202/84590b4a-e247-4c10-8ca8-e13339b29a2c)

I've tested it in chrome on windows and mac.
Does it happen only on your computer? or does it happen on other computers as well?

**Comment by oas777** [comment]
Yes, it seems to be a resolution issue only with 1920 x 1080 - which is a standard though, so weird for Chrome to have issues Firefox hasn't got.
I also checked the available viewing space in the browser, cf. https://whatismyviewport.com/. Firefox has  1280 × 531 (and no problems), Chrome 1280 × 595 and issues.

**Comment by miesgre** [comment]
Are you using zoom in chrome?
I only can reproduce it if I put a 67% zoom in chrome, but not in 100%

ctrl + +
crtl + -

**Comment by oas777** [comment]
Genius! Zoom was at 90%. Sorry for the confusion.

**Comment by miesgre** [comment]
I suppressed the line breaks. It should work now in chrome 90%

**Comment by oas777** [comment]
Correct!
