### ISSUE TITLE
Forward and backward button indicates "10 seconds" but jumps 30 seconds

### ISSUE THREAD

**Issue by cgruber-uos** [polimediaupv/paella-ethz#5]
The forward and backward button has a "10" [seconds] text on the visual button. But by clicking it jumps 30 seconds. **We should adjust the jumping time to 10 seconds.** Tooltip indicates also 30 seconds and must be adjusted to 10: 

![2022-12-12 12_49_37-Greenshot](https://user-images.githubusercontent.com/101632236/207038486-2d099b82-71c6-46a7-b3b3-03dddad73fb3.png)

Just as reference: **YouTube** has also a **10 second leap** for the shortcut "l" / "j" and aditional 5 seconds for  
- l (10s) / cursor right (5s)
- j (10s) /  cursor left (5s)

Remark @naweidner: We should align the leap to the same time in OC Studio if there it is not 10 seconds. OC Editor has currently a jumping time of 1 second. But due to a cutting tool this makes sense and should not be changed to a lager time.

**Comment by miesgre** [comment]
Fixed in commit f152cb56fe4206c6c3ec7e4c72cc0f0f1ca11d23

Test it in: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote

**Comment by oas777** [comment]
Looks good to me.

**Comment by cgruber-uos** [comment]
Thx for fixing!
