### ISSUE TITLE
Omit "key"... in English shortcut list 

### ISSUE THREAD

**Issue by cgruber-uos** [polimediaupv/paella-ethz#7]
The shortcut table has "key" as prefix before the actual key, I think we can omit "key" and just write the shortcut for better readability: 

![2022-12-12 13_35_21-Greenshot](https://user-images.githubusercontent.com/101632236/207047466-6980b0ef-c933-4ec9-852a-576f47dd3645.png)

We may format the shortcut also in a more keyboard like design as done in OC Studio: 

![2022-12-12 13_39_20-Opencast Studio – Mozilla Firefox](https://user-images.githubusercontent.com/101632236/207047492-f84a3e4e-dc8c-48be-8d24-981e2bc61062.png)

**Comment by miesgre** [comment]
Translations added in commit bb4f1136d1497de3fae3ce8099f02fc0b438c28f
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote

**Comment by oas777** [comment]
Confirmed, thanks. But you have to change

Rewind 30 seconds
Forward 30 seconds 

to "10 seconds".

**Comment by miesgre** [comment]
Text changed and keys rewind/forward 10 seconds

**Comment by oas777** [comment]
Looks good, thanks!

**Comment by ClemensGruber** [comment]
There is still "key" as prefix before the actual key, can we omit "key" and just write the shortcut for better readability. Tested on: 

> Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote

**Comment by miesgre** [comment]
Thanks @ClemensGruber. Do you have your browser in German? I think it is due to the lack of translation strings.

**Comment by ClemensGruber** [comment]
My local browser has a German UI, do we not have a German Translation for the Paella? And even in the Englisch / default / not translated version we should not use "key" as prefix.

**Comment by miesgre** [comment]
Thanks @ClemensGruber! Now the "default" language (English) is used if there is no translation for the users language.
