### ISSUE TITLE
Playback Speed shortcut "O" loops endless

### ISSUE THREAD

**Issue by cgruber-uos** [polimediaupv/paella-ethz#8]
The playback Speed **shortcut "O"** -- "increase playback speed" -- loops through the possible speed settings **endless**

_1x > 1.5x > 2x > [new start at] 0x > 0.75x > 1x > 1.5x > 2x ..._ and so on! 

**Expected behavior: it should stop at 2x, the fastest speed possible.** 

The **speed 0x** makes no sense, does not show up in the "playback rate" menu (see screenshot below) and should be deleted! 

Shortcut "O" makes all right and stopps at "0.75x"! 

![2022-12-12 13_46_42-](https://user-images.githubusercontent.com/101632236/207048741-96458358-c127-4bbf-a77b-c31c7e3043fe.png)

Btw. playback speed list seems to me illogical because the slow speed (0.75x) is on top while the fast speed is at the bottom, would expect fast on top and slower speed beneath. 

![2022-12-12 13_48_44-Paella Player 7 – Mozilla Firefox](https://user-images.githubusercontent.com/101632236/207049088-f4c009e7-cbd1-475f-8f65-0e2597bf5325.png)

But same on YouTube: 

![2022-12-12 14_03_53-Greenshot](https://user-images.githubusercontent.com/101632236/207052175-7448c8a2-f7cc-439c-a9de-36168a45af9a.png)

**Comment by miesgre** [comment]
Fixed!
Demo: https://polimediaupv.github.io/paella-ethz/?id=belmar-multiresolution-remote

**Comment by oas777** [comment]
Works on Firefox and Chrome (Windows).
